config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :articles
  root 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  attr_accessor :min_price
  attr_accessor :max_price

  belongs_to :category
  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  attr_accessor :login

  validates :username,presence: true, uniqueness: {case_sensitive: false },format: {with: /\A[a-zA-Z0-9 _\.]*\z/ }
  validates :phone, length: 10..13


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where("lower(username)= :value OR lower(email)=:value",value: login.downcase).first
    else
      where(conditions.to_hash).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up){ |m| m.permit(:username,:email, :password, :password_confirmation, :phone)}
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id=current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :content, :price, :image, :category_id, :user_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :content %>
    <%= f.input :price %>
    <%= f.association :category,include_blank: false %>
  </div>

  <%= f.input :image, as: :file%>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/_form_selection.html.erb
<div class="formSelection">
  <%= form_with model: @articles,url: articles_path, method: "get", class: "" do |f| %>
    <div class="researchDiv">

      <%= f.text_field :name, placeholder: "Que recherchez-vous?",value: "",class:'valueResearch' %>
      <%= f.button  :submit,label:"recherche" ,class:'form-actions',class: 'buttonResearch'%>
    </div>
    <div class="parameterResearch">
      <%= f.text_field :min_price,include_blank: false, placeholder: "prix minimum" %>
      <%= f.text_field :max_price,include_blank: false, placeholder: "prix maximum" %>
      <%= f.select :category_id, Category.all.collect {|p| [ p.name, p.id ] }, { include_blank: false } %>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'form_selection', articles: @articles,categories: @categories %>


<% @articles.each do |article| %>
  <div style="display:flex;flex-direction: row;">
    <a href="<%=article_path(article) %>" style="flex:1;">
      <div class="" style="display:flex;flex-direction: row;justify-content:space-around;border: 1px solid #666666;border-radius: 5px;;margin: 10px;padding: 5px;">
        <div class="">
          <div><%= image_tag article.image_url(:thumb) %></div>
        </div>
        <div class="IndexDiv"  style="display:flex;flex-direction: column;justify-content:space-between;min-height: 50px;">
          <div><%= article.name %></div>
          <div><%= article.price %></div>

          <div><%= article.category.name %></div>
          <div><%= article.created_at %></div>

        </div>

      </div>
    </a>
    <% if user_signed_in? && current_user.id == article.user_id %>
      <div class="" style="flex:0;min-width: 100px;display: flex;flex-direction: column;justify-content: space-around">

          <%= link_to 'Edit', edit_article_path(article), class:'btn btn-primary' %>
          <%= link_to 'Destroy', article, method: :delete, class:'btn btn-warning', data: { confirm: 'Are you sure?' } %>

      </div>
    <%end %>
  </div>

<% end %>

<% if user_signed_in?%>
  <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Price:</strong>
  <%= @article.price %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leboncanard</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<header>

</header>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=root_path%>">Leboncanard</a>
  <button class="navbar-toggler" type="button"  aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ">
      <% if user_signed_in? %>
        <a class="nav-item nav-link active" href="<%=edit_user_password_path%>"><%=current_user.username %><span class="sr-only">(current)</span></a>
        <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: "nav-item nav-link active" %>
      <%else %>
        <a class="nav-item nav-link active" href="<%=user_session_path%>">Se connecter<span class="sr-only">(current)</span></a>
      <%end %>
    </div>
  </div>
</nav>
  <% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= notice %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-info" role="alert"><%= alert %></div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
<footer>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</footer>
</html>